// gameSeq → what the game says
// userSeq → what the user repeats
// levelUp() → adds one new step
// checkAns() → verifies user input
// reset() → restarts everything


// gameSeq → what the game says
// userSeq → what the user repeats
// levelUp() → adds one new step
// checkAns() → verifies user input
// reset() → restarts everything


// Stores the sequence generated by the game
let gameSeq = [];

// Stores the sequence clicked by the user
let userSeq = [];

// Tracks whether the game has started
let started = false;

// Keeps track of the current level
let level = 0;

// Selects the h2 element used for displaying messages
let h2 = document.querySelector("h2");

// Selects the Start button
let startBtn = document.querySelector("#start-btn");

// Array containing all button colors
let btns = ["red", "yellow", "green", "purple"];

// Function to start the game
function startGame() {

    // Prevents the game from starting multiple times
    if (started == false) {

        // Marks the game as started
        started = true;

        // Hides the Start button after starting
        startBtn.style.display = "none";

        // Moves to the first level
        levelUp();
    }
}

// Starts the game when any key is pressed
document.addEventListener("keypress", function () {
    startGame();
});

// Starts the game when Start button is clicked
startBtn.addEventListener("click", function () {
    startGame();
});

// Creates flash animation for game-generated button
function gameFlash(btn) {

    // Adds flash effect class
    btn.classList.add("flash");

    // Removes flash effect after 250ms
    setTimeout(function () {
        btn.classList.remove("flash");
    }, 250);
}

// Creates flash animation for user-clicked button
function userFlash(btn) {

    // Adds user flash effect class
    btn.classList.add("userflash");

    // Removes effect after 250ms
    setTimeout(function () {
        btn.classList.remove("userflash");
    }, 250);
}

// Increases level and generates next sequence color
function levelUp() {

    // Clears user's previous inputs
    userSeq = [];

    // Increments level count
    level++;

    // Displays current level on screen
    h2.innerText = `Level ${level}`;

    // Generates a random index
    let randIdx = Math.floor(Math.random() * btns.length);

    // Gets random color using the index
    let randClr = btns[randIdx];

    // Adds random color to game sequence
    gameSeq.push(randClr);

    // Selects the corresponding color button
    let randBtn = document.querySelector(`.${randClr}`);

    // Flashes the selected button
    gameFlash(randBtn);
}

// Checks whether user's answer is correct
function checkAns(idx) {

    // Compares latest user input with game sequence
    if (userSeq[idx] === gameSeq[idx]) {

        // Checks if user completed the whole sequence
        if (userSeq.length == gameSeq.length) {

            // Moves to next level after 1 second
            setTimeout(levelUp, 1000);
        }
    } else {

        // Displays game over message and score
        h2.innerHTML = `Game Over! Your score was <b>${level}</b> <br> Press any key or tap Start again.`;

        // Changes background to red on wrong answer
        document.querySelector("body").style.backgroundColor = "red";

        // Restores original background color
        setTimeout(function () {
            document.querySelector("body").style.backgroundColor = "";
        }, 150);

        // Resets the game
        reset();
    }
}

// Runs whenever a game button is clicked
function btnPress() {

    // Stores the clicked button element
    let btn = this;

    // Shows click animation
    userFlash(btn);

    // Gets the button's color id
    let userClr = btn.getAttribute("id");

    // Adds user's color choice to sequence
    userSeq.push(userClr);

    // Checks the latest answer
    checkAns(userSeq.length - 1);
}

// Selects all color buttons
let allBtns = document.querySelectorAll(".btn");

// Adds click event listener to every button
for (btn of allBtns) {
    btn.addEventListener("click", btnPress);
}

// Resets all game variables
function reset() {

    // Marks game as not started
    started = false;

    // Clears game sequence
    gameSeq = [];

    // Clears user sequence
    userSeq = [];

    // Resets level count
    level = 0;

    // Shows Start button again
    startBtn.style.display = "inline-block";
}