// gameSeq → what the game says
// userSeq → what the user repeats
// levelUp() → adds one new step
// checkAns() → verifies user input
// reset() → restarts everything


// Array to store the sequence generated by the game
let gameSeq = [];

// Array to store the sequence entered by the user
let userSeq = [];

// Flag to check if the game has started
let started = false;

// Variable to keep track of the current level
let level = 0;

// Select the <h2> element to display level / messages
let h2 = document.querySelector("h2");

// Array of button colors (used for random selection)
let btns = ["red", "yellow", "green", "purple"];

// Start the game when any key is pressed (only once)
document.addEventListener("keypress", function () {
    if (started == false) {
        started = true;     // mark game as started
        levelUp();          // begin first level
    }
});

// Function to flash a button for game sequence
function gameFlash(btn) {
    btn.classList.add("flash");  // add flash effect

    setTimeout(function () {
        btn.classList.remove("flash"); // remove after 250ms
    }, 250);
}

// Function to flash a button when user clicks
function userFlash(btn) {
    btn.classList.add("userflash"); // add user click effect

    setTimeout(function () {
        btn.classList.remove("userflash"); // remove after 250ms
    }, 250);
}

// Function to move to the next level
function levelUp() {
    userSeq = [];  // reset user sequence for new level

    level++;  // increase level
    h2.innerText = `Level ${level}`; // update level text

    // Generate random color index
    let randIdx = Math.floor(Math.random() * btns.length);

    // Get random color using index
    let randClr = btns[randIdx];

    // Add this color to game sequence
    gameSeq.push(randClr);

    // Select the corresponding button element
    let randBtn = document.querySelector(`.${randClr}`);

    // Flash the button to show the sequence
    gameFlash(randBtn);
}

// Function to check user's answer step by step
function checkAns(idx) {
    // Check if current user input matches game sequence
    if (userSeq[idx] === gameSeq[idx]) {

        // If user completed the whole sequence correctly
        if (userSeq.length == gameSeq.length) {
            setTimeout(levelUp, 1000); // move to next level after delay
        }

    } else {
        // If wrong input → Game Over
        h2.innerHTML = `Game Over! Your score was <b>${level}</b> <br> Press any key to start again.`;

        // Flash red background for feedback
        document.querySelector("body").style.backgroundColor = "red";

        setTimeout(function () {
            document.querySelector("body").style.backgroundColor = "";
        }, 150);

        reset(); // reset game
    }
}

// Function executed when user presses a button
function btnPress() {
    let btn = this; // current button clicked

    userFlash(btn); // show click effect

    // Get color id of clicked button
    let userClr = btn.getAttribute("id");

    // Add user choice to user sequence
    userSeq.push(userClr);

    // Check if the answer is correct so far
    checkAns(userSeq.length - 1);
}

// Select all buttons
let allBtns = document.querySelectorAll(".btn");

// Add click event listener to each button
for (btn of allBtns) {
    btn.addEventListener("click", btnPress);
}

// Function to reset the game after Game Over
function reset() {
    started = false;  // allow restart

    gameSeq = [];     // clear game sequence
    userSeq = [];     // clear user sequence
    level = 0;        // reset level
}



